config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    #help_path → '/help' → static_pages#help → helpビュー表示
  	get  '/help',    to: 'static_pages#help'
  	get  '/about',   to: 'static_pages#about'
  	get  '/contact', to: 'static_pages#contact'
  	get  '/signup',  to: 'users#new'

    #Sessionのルーティングはフルセットにする必要がないため、名前付きのルーティングを記載
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    resources :users do
    member do
      get :following, :followers
    end
  end
    # リソースをeditのみにする,GET  /account_activation/トークン/edit edit  edit_account_activation_url(token)
    resources :account_activations, only: [:edit]
    # パスワードリセット用ルーティング
    resources :password_resets,     only: [:new, :create, :edit, :update]
    # micropostsルーティング
    resources :microposts,          only: [:create, :destroy]
    # フォロー,フォロワー
    resources :relationships,       only: [:create, :destroy]
    # resources一覧, rails routesで全てのルーティングを確認可能
    # GET	/users	index	users_path	すべてのユーザーを一覧するページ
	  # GET	/users/1	show	user_path(user)	特定のユーザーを表示するページ
	  # GET	/users/new	new	new_user_path	ユーザーを新規作成するページ（ユーザー登録）
	  # POST	/users	create	users_path	ユーザーを作成するアクション
	  # GET	/users/1/edit	edit	edit_user_path(user)	id=1のユーザーを編集するページ
	  # PATCH	/users/1	update	user_path(user)	ユーザーを更新するアクション
	  # DELETE	/users/1	destroy	user_path(user)	ユーザーを削除するアクション
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
      <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app",root_path, id: "logo" %>
        
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",root_path %></li>
            <!-- help_path → ルーティングの'/help' → static_pages#help → helpビュー表示 -->
            <li><%= link_to "Help",help_path %></li>

        <% if logged_in? %>
          <!-- ユーザー一覧,user_pathでなくusers_path -->
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <!-- current_user = user_path(current_user) -->
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <!-- method: :deleteはデフォルトのGetリクエストをDELETEに変更 -->
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- IEのバージョンが9より小さい場合（if lt IE 9の下)適応する -->
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
<!-- full_titleを呼び出す、yieldの引数には各ビューのprovide(:title ,"*")を受け取り設定 -->
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    
    <!-- views/layouts/_shim.html.erbを読み込む -->
     <%= render 'layouts/shim' %>
    
  </head>
  <body>
  
       <!-- views/layouts/_header.html.erbを読み込む -->
        <%= render 'layouts/header' %>
        
    <div class="container">

      <!-- flash,each内の|message_type => key:success message => valiu:"登録成功" -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <!-- views/layouts/_footer.html.erbを読み込む -->
      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
      
    </div>
    
  </body>
</html>